apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-client-config
  namespace: keycloak
data:
  vault-client-payload.json: |
    {
      "clientId": "vault",
      "name": "HashiCorp Vault",
      "description": "OIDC client for HashiCorp Vault authentication",
      "enabled": true,
      "clientAuthenticatorType": "client-secret",
      "secret": "vault-client-secret-123",
      "redirectUris": [
        "https://vault.cnoe.localtest.me/ui/vault/auth/oidc/oidc/callback",
        "http://localhost:8250/oidc/callback"
      ],
      "webOrigins": [
        "https://vault.cnoe.localtest.me",
        "http://localhost:8250"
      ],
      "standardFlowEnabled": true,
      "implicitFlowEnabled": false,
      "directAccessGrantsEnabled": true,
      "serviceAccountsEnabled": false,
      "publicClient": false,
      "frontchannelLogout": true,
      "protocol": "openid-connect",
      "attributes": {
        "saml.assertion.signature": "false",
        "saml.force.post.binding": "false",
        "saml.multivalued.roles": "false",
        "saml.encrypt": "false",
        "saml.server.signature": "false",
        "saml.server.signature.keyinfo.ext": "false",
        "exclude.session.state.from.auth.response": "false",
        "saml_force_name_id_format": "false",
        "saml.client.signature": "false",
        "tls.client.certificate.bound.access.tokens": "false",
        "saml.authnstatement": "false",
        "display.on.consent.screen": "false",
        "saml.onetimeuse.condition": "false"
      },
      "authenticationFlowBindingOverrides": {},
      "fullScopeAllowed": true,
      "nodeReRegistrationTimeout": -1,
      "defaultClientScopes": [
        "web-origins",
        "role_list",
        "profile",
        "roles",
        "email",
        "groups"
      ],
      "optionalClientScopes": [
        "address",
        "phone",
        "offline_access",
        "microprofile-jwt"
      ]
    }
  vault-groups-payload.json: |
    {
      "name": "vault-admins",
      "path": "/vault-admins"
    }
  vault-developers-payload.json: |
    {
      "name": "vault-developers", 
      "path": "/vault-developers"
    }
